server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json, application/x-protobuf

application:
  name: envoy-control

envoy-control:
  source:
    consul:
      host: localhost

management:
  endpoint:
    metrics.enabled: true
    prometheus.enabled: true
  endpoints.web.exposure.include: "*"
  metrics.export.prometheus.enabled: true